### PR TITLE
Building with Backgrounds and Gradients [Solo Project] Pull Request

### PR DESCRIPTION
**Pull request by kubilaycaglayan**
[Click For Live Page](https://raw.githack.com/kblycaglayan/apple-clone/apple-clone/index.html)

_Apple page recreated according to the specifics._
**Gradient** backgrounding satisfied whilst forming _navbar_.
Background visual positioned as a **background image**.

Thanks for your time and efforts.
With all my respect...

### CODE REVIEW

**Review by nikasulo — COMMENTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# This is really awesome work @kblycaglayan :medal_military: 
Your project is beautiful and you have met most of the requirements for this project. There is, however, on detail that requires your attention. 

Please consider that the original website is a full-width page(browser edge to browser edge), I have encountered a few of these issues before and there seems to be another version that students look at, but the version accepted by Microverse is the full-width version. 

Please consider making the tiny adjustment to your layout and request another review, I wish you the very best and see you at the top!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by kubilaycaglayan** [comment]
[Click For The Live Link](https://rawcdn.githack.com/kblycaglayan/apple-clone/e2537bb1bb06102cb8c059565540fe9107705304/index.html)

**Edge to Edge Fit:** 
**To achieve this, I changed the 
**width:  pixels** 
with the 
**width:  percentage** . 

And to protect the overall visuality, I wrote **max-width** to the container.

With all my respect...

**Review by nikasulo — APPROVED** [review]
# Congratulations @kblycaglayan ! :medal_military: 
I have no words for how awesome your work is! Please merge and keep moving forward with the same level of attention to detail. I wish you all the best and I will see you at the top definitely! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
